name: deploy

on:
  push:
    branches: master  

      
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Build and push to Docker Hub
      uses: docker/login-action@v2    
      with:
          username: ${{ secrets.DOCKER_USERNAME }}myrotvorets/kubectl-action
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          #repository: ${{ udecdj2022/prueba-gha:v1 }}
          #tag_with_ref: true
          #tag_with_sha: true
          #tags: ${{ github.sha }}        

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/prueba-gha:latest

    - uses: actions/checkout@v2
    - name: deploy to cluster in kubernetes
      uses: myrotvorets/kubectl-action@2.0.0
      with: 
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: latest  
            #command: set image --record deployment/prueba-gha prueba-gha=${{ github.repository }}:${{ github.sha }}
          args: set image --record deployment/prueba-gha prueba-gha=${{ github.repository }}:latest
            
    - name: restart deployment in kubernetes
      uses: myrotvorets/kubectl-action@2.0.0
      with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: latest 
          args: rollout restart deployment/prueba-gha
    
    - name: Check deployment in kubernetes
      uses: myrotvorets/kubectl-action@2.0.0
      with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: latest
          args: rollout status deployment/prueba-gha


